/**
 * Generate the files a factory's service is built from.
 *
 * @packageDocumentation
 */

import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { checkFactoryIntegration } from "../build/integration.ts";
import { GENERATED_DIR, GENERATED_ENTRY_FILE, GENERATED_PLUGIN_FILE } from "./generated-files.ts";

export { generateFactoryIntegration } from "../build/integration.ts";

// A real entry file, never a nitro alias: the workflow builder runs its own
// discovery pass that does not honour nitro aliases, so an alias would build
// clean for Nitro and silently emit a manifest with no steps in it.
//
// Generated every build rather than scaffolded once by `jigs init`, even
// though the content does not vary today: this is jigs' own code sitting in
// the factory's tree. A copy made at init time would go stale in every
// existing factory the day this seam changes, with nothing to say so.
//
// Workflow modules load only in the compiled service. Literal deferred imports
// remain in jigs.config.ts for the SDK's discovery/build pass to follow.
const ENTRY_SOURCE = `// Generated by \`jigs build\` — do not edit.
import type { Factory, FactoryDefinition } from "@jigs-ai/jigs";
import { createApp } from "@jigs-ai/jigs/service";
import config from "../jigs.config.ts";

const definition: FactoryDefinition = config;
const workflows = Object.fromEntries(await Promise.all(
  Object.entries(definition.workflows).map(async ([name, load]) => [name, (await load()).default]),
));
export const factory = {
  workflows,
  schedules: definition.schedules,
  triggers: definition.triggers,
  webhooks: definition.webhooks,
} satisfies Factory;

export default createApp(factory);
`;

// A nitro plugin rather than a line in the entry above, so the service starts
// when Nitro boots rather than when the route module is evaluated. It has to
// live here because only the factory's own tree can import its compiled
// workflows.
const PLUGIN_SOURCE = `// Generated by \`jigs build\` — do not edit.
import { startService } from "@jigs-ai/jigs/service";
import { factory } from "./${GENERATED_ENTRY_FILE}";

export default () => {
  startService(factory);
};
`;

/**
 * Writes everything a factory's Nitro build needs but does not keep in git,
 * under `<factoryRoot>/.jigs/`, and returns the entry's absolute path. The
 * directory is rewritten in full, so running this twice is running it once.
 */
export function prepare(factoryRoot: string): string {
  checkFactoryIntegration(factoryRoot);
  const generated = path.join(factoryRoot, GENERATED_DIR);
  // Files an earlier release generated would otherwise linger for the
  // workflow builder's scan to trip over.
  rmSync(generated, { recursive: true, force: true });
  mkdirSync(generated, { recursive: true });

  const entry = path.join(generated, GENERATED_ENTRY_FILE);
  writeFileSync(entry, ENTRY_SOURCE);
  writeFileSync(path.join(generated, GENERATED_PLUGIN_FILE), PLUGIN_SOURCE);
  return entry;
}
