/**
 * Generate and build the service files that host a factory.
 *
 * @packageDocumentation
 */

import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { checkFactoryIntegration } from "../cli/integration.ts";

export { generateFactoryIntegration } from "../cli/integration.ts";

/** Where `prepare()` writes the generated sources, relative to the factory
 *  root. `nitro.ts` imports them to point its route and plugin at the same
 *  files. */
export const GENERATED_DIR = ".jigs";
/** Generated Nitro route filename within the factory's `.jigs` directory. */
export const GENERATED_ENTRY_FILE = "server.ts";
/** Generated schedule plugin filename within the factory's `.jigs` directory. */
export const GENERATED_SCHEDULES_FILE = "schedules.ts";
/** Generated automatic-release plugin filename within the factory's `.jigs` directory. */
export const GENERATED_CLEANUP_FILE = "automatic-release.ts";

// A real entry file, never a nitro alias: the workflow builder runs its own
// discovery pass that does not honour nitro aliases, so an alias would build
// clean for Nitro and silently emit a manifest with no steps in it.
//
// Generated every build rather than scaffolded once by `jigs init`, even
// though the content does not vary today: this is jigs' own code sitting in
// the factory's tree. A copy made at init time would go stale in every
// existing factory the day this seam changes, with nothing to say so.
const ENTRY_SOURCE = `// Generated by \`jigs build\` — do not edit.
import { createApp } from "@jigs-ai/jigs/app";
import factory from "./factory.ts";

export default createApp(factory);
`;

// A nitro plugin rather than a line in the entry above, so the ticker starts
// beside the World it fires runs into rather than when the route module is
// evaluated. It has to live here because only the factory's own tree can
// import its compiled workflows.
const SCHEDULES_SOURCE = `// Generated by \`jigs build\` — do not edit.
import { startSchedules } from "@jigs-ai/jigs/schedules";
import factory from "./factory.ts";

export default () => {
  startSchedules(factory);
};
`;

const CLEANUP_SOURCE = `// Generated by \`jigs build\` — do not edit.
import { startAutomaticRelease } from "@jigs-ai/jigs/automatic-release";
import factory from "./factory.ts";

export default () => {
  startAutomaticRelease(factory);
};
`;

// Load workflow modules only in the compiled service. Literal deferred imports
// remain in jigs.config.ts for the SDK's discovery/build pass to follow.
const FACTORY_SOURCE = `// Generated by \`jigs build\` — do not edit.
import type { Factory, FactoryDefinition } from "@jigs-ai/jigs";
import config from "../jigs.config.ts";

const definition: FactoryDefinition = config;
const workflows = Object.fromEntries(await Promise.all(
  Object.entries(definition.workflows).map(async ([name, load]) => [name, (await load()).default]),
));
export default { workflows, schedules: definition.schedules } satisfies Factory;
`;

/**
 * Writes everything a factory's Nitro build needs but does not keep in git,
 * under `<factoryRoot>/.jigs/`, and returns the entry's absolute path. The
 * file is rewritten in full, so running this twice is running it once.
 */
export function prepare(factoryRoot: string): string {
  checkFactoryIntegration(factoryRoot);
  const generated = path.join(factoryRoot, GENERATED_DIR);
  mkdirSync(generated, { recursive: true });

  writeFileSync(path.join(generated, "factory.ts"), FACTORY_SOURCE);
  const entry = path.join(generated, GENERATED_ENTRY_FILE);
  writeFileSync(entry, ENTRY_SOURCE);
  writeFileSync(path.join(generated, GENERATED_SCHEDULES_FILE), SCHEDULES_SOURCE);
  writeFileSync(path.join(generated, GENERATED_CLEANUP_FILE), CLEANUP_SOURCE);
  return entry;
}
