import { defineJigsService } from "./src/nitro.ts";

// This package's own build goes through the same helper a factory repo uses,
// with its entry named explicitly: the demo factory's composition root is
// committed here rather than generated by `jigs build`.
export default defineJigsService({ entry: "./src/server.ts" });
