import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, expect, test } from "vitest";
import { checkFactoryIntegration, generateFactoryIntegration } from "./integration.ts";

const roots: string[] = [];
function factory() {
  const root = mkdtempSync(path.join(tmpdir(), "jigs-integration-"));
  roots.push(root);
  return root;
}
afterEach(() => {
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true });
});

test("generation is repeatable and build validation never overwrites drift", () => {
  const root = factory();
  expect(() => checkFactoryIntegration(root)).toThrow(/missing or differs/);
  const [file] = generateFactoryIntegration(root) as [string, string];
  const generated = readFileSync(file, "utf8");
  checkFactoryIntegration(root);
  generateFactoryIntegration(root);
  expect(readFileSync(file, "utf8")).toBe(generated);

  const customized = `${generated}\n// custom code belongs elsewhere\n`;
  writeFileSync(file, customized);
  expect(() => checkFactoryIntegration(root)).toThrow(/missing or differs/);
  expect(readFileSync(file, "utf8")).toBe(customized);

  generateFactoryIntegration(root);
  checkFactoryIntegration(root);
  expect(readFileSync(file, "utf8")).toBe(generated);
});

// The one write jigs must never repeat blind. The SDK reads `maxRetries` off
// the step function, so the property has to survive into the factory's own
// file — a generated wrapper without it retries a POST that may already have
// posted.
test("the pull request POST wrappers are generated single-attempt", () => {
  const [steps] = generateFactoryIntegration(factory()) as [string, string];
  const generated = readFileSync(steps, "utf8");
  expect(generated).toContain("replyToPullRequestReviewThread.maxRetries = 0;");
  expect(generated).toContain("commentOnPullRequest.maxRetries = 0;");
});

test("steps.ts holds every step directive, and routines.ts holds none", () => {
  const root = factory();
  generateFactoryIntegration(root);
  expect(readFileSync(path.join(root, "jigs/steps.ts"), "utf8")).toContain('"use step"');
  const routines = readFileSync(path.join(root, "jigs/routines.ts"), "utf8");
  expect(routines).not.toContain('"use step"');
  expect(routines).not.toMatch(/export const (agent|linear|pullRequest)Steps/);
  expect(existsSync(path.join(root, "jigs/index.ts"))).toBe(false);
});

test("a build refuses a factory that still holds the old generated file", () => {
  const root = factory();
  generateFactoryIntegration(root);
  writeFileSync(path.join(root, "jigs.ts"), "// generated by an earlier jigs\n");
  expect(() => checkFactoryIntegration(root)).toThrow(/no longer generated/);
});
