export const sharedOptions = {
  blockTags: ["@example", "@group", "@inlineType", "@module", "@remarks"],
  disableSources: true,
  entryPointStrategy: "resolve",
  excludeInternal: true,
  githubPages: false,
  groupOrder: [
    "Factory and workflows",
    "Harnesses and models",
    "Agents and models",
    "Agent and model requests/results",
    "Decision models",
    "Human input",
    "Linear tickets",
    "Linear and human input",
    "Pull requests",
    "Git/change data",
    "Git changes",
    "Runtime and resources",
    "Errors and utilities",
    "Agent runner",
    "Errors",
    "Advanced driver contracts",
    "Runtime metadata",
    "Execution primitives",
    "Agent execution",
    "Workspaces and resources",
    "Inspect changes",
    "Publish changes",
    "Resolve and read",
    "Create and update",
    "Human interaction primitives",
    "Rendering/customization",
    "Read",
    "Open/update",
    "Discuss/review",
    "Merge",
    "Run directories",
    "Recorded resources",
    "Release",
    "Advanced run context",
    "Worktrees",
    "Advanced implementation/testing",
    "*",
  ],
  includeVersion: true,
  inlineTags: ["@link"],
  modifierTags: ["@internal", "@packageDocumentation"],
  readme: "none",
  treatValidationWarningsAsErrors: true,
  treatWarningsAsErrors: true,
  validation: {
    invalidLink: true,
    invalidPath: true,
    notDocumented: false,
    notExported: false,
    rewrittenLink: true,
    unusedMergeModuleWith: true,
  },
};

export const typedocOptions = {
  ...sharedOptions,
  entryFileName: "index",
  hideBreadcrumbs: true,
  hidePageHeader: true,
  router: "module",
};

export default typedocOptions;

// Site-only: tables and code-block signatures scan well in a browser, while the
// npm pages under docs/api keep the default layout that reads well as plain text.
export const siteOptions = {
  // Match TypeDoc's symbol links even when group ordering differs from conversion order.
  useCustomAnchors: true,
  classPropertiesFormat: "table",
  enumMembersFormat: "table",
  interfacePropertiesFormat: "table",
  parametersFormat: "table",
  sortEntryPoints: false,
  tableColumnSettings: {
    hideDefaults: false,
    hideInherited: true,
    hideModifiers: true,
    hideOverrides: true,
    hideSources: true,
    leftAlignHeaders: true,
  },
  typeAliasPropertiesFormat: "table",
  typeDeclarationFormat: "table",
  useCodeBlocks: true,
};
