/**
 * Generate the files a factory's service is built from.
 *
 * @packageDocumentation
 */

import { copyFileSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { packageRoot } from "../build/templates.ts";
import { GENERATED_DIR, GENERATED_ENTRY_FILE, GENERATED_PLUGIN_FILE } from "./generated-files.ts";

// A real entry file, never a nitro alias: the workflow builder runs its own
// discovery pass that does not honour nitro aliases, so an alias would build
// clean for Nitro and silently emit a manifest with no steps in it.
//
// Generated every build rather than scaffolded once by `jigs init`, even
// though the content does not vary today: this is jigs' own code sitting in
// the factory's tree. A copy made at init time would go stale in every
// existing factory the day this seam changes, with nothing to say so.
//
// Workflow modules load only in the compiled service. Literal deferred imports
// remain in jigs.config.ts for the SDK's discovery/build pass to follow.
const ENTRY_SOURCE = `// Generated by \`jigs build\` — do not edit.
import type { Factory, FactoryDefinition } from "@jigs-ai/jigs";
import { createApp } from "@jigs-ai/jigs/service";
import config from "../jigs.config.ts";

const definition: FactoryDefinition = config;
const workflows = Object.fromEntries(await Promise.all(
  Object.entries(definition.workflows).map(async ([name, load]) => [name, (await load()).default]),
));
export const factory = {
  workflows,
  schedules: definition.schedules,
  triggers: definition.triggers,
} satisfies Factory;

export default createApp(factory);
`;

// A nitro plugin rather than a line in the entry above, so the service starts
// when Nitro boots rather than when the route module is evaluated. It has to
// live here because only the factory's own tree can import its compiled
// workflows. Nitro's server entry reads PORT only after every plugin module
// has been evaluated, so the top level here sets it in time.
const PLUGIN_SOURCE = `// Generated by \`jigs build\` — do not edit.
import { listenOnServicePort, startService } from "@jigs-ai/jigs/service";
import config from "../jigs.config.ts";
import { factory } from "./${GENERATED_ENTRY_FILE}";

listenOnServicePort();

export default () => {
  startService(factory, config);
};
`;

/**
 * Writes everything a factory's Nitro build needs but does not keep in git,
 * under `<factoryRoot>/.jigs/`, and returns the entry's absolute path. The
 * directory is rewritten in full, so running this twice is running it once.
 */
export function prepare(factoryRoot: string): string {
  const generated = path.join(factoryRoot, GENERATED_DIR);
  // Files an earlier release generated would otherwise linger for the
  // workflow builder's scan to trip over.
  rmSync(generated, { recursive: true, force: true });
  mkdirSync(generated, { recursive: true });

  const entry = path.join(generated, GENERATED_ENTRY_FILE);
  writeFileSync(entry, ENTRY_SOURCE);
  writeFileSync(path.join(generated, GENERATED_PLUGIN_FILE), PLUGIN_SOURCE);
  // Copied into the factory so each step's durable ID is a factory path,
  // which upgrading jigs cannot rename (ADR 0006).
  for (const file of ["steps.ts", "routines.ts"]) {
    copyFileSync(path.join(packageRoot(), "factory", file), path.join(generated, file));
  }
  return entry;
}

/**
 * A Vitest plugin that writes `.jigs/` before tests run, so a test that imports `#jigs/steps`
 * or `#jigs/routines` finds the files the service build would write.
 */
export function prepareJigs() {
  return {
    name: "jigs:prepare",
    config(config: { root?: string }) {
      prepare(path.resolve(config.root ?? process.cwd()));
    },
  };
}
