import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, expect, test } from "vitest";
import { generateIntegration, migrateRetiredLayout } from "./generate.ts";

const roots: string[] = [];
function factory() {
  const root = mkdtempSync(path.join(tmpdir(), "jigs-generate-"));
  roots.push(root);
  writeFileSync(path.join(root, "jigs.config.ts"), "export default {};");
  writeFileSync(
    path.join(root, "package.json"),
    JSON.stringify({ name: "acme", imports: { "#jigs/*": "./jigs/*.ts" } }),
  );
  return root;
}
afterEach(() => {
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true });
});

test("generation comes from the factory's installed package, even from a subdirectory", async () => {
  const root = factory();
  const packageDir = path.join(root, "node_modules/@jigs-ai/jigs");
  mkdirSync(packageDir, { recursive: true });
  writeFileSync(
    path.join(packageDir, "package.json"),
    JSON.stringify({
      name: "@jigs-ai/jigs",
      type: "module",
      exports: { "./build": "./build.js" },
    }),
  );
  writeFileSync(
    path.join(packageDir, "build.js"),
    `
import { writeFileSync } from 'node:fs';
import path from 'node:path';
export function generateFactoryIntegration(root) {
  writeFileSync(path.join(root, 'jigs-generated.ts'), '// this factory installed me');
}
`,
  );
  const nested = path.join(root, "workflows");
  mkdirSync(nested);
  const lines: string[] = [];
  await generateIntegration({ cwd: nested, out: (line) => lines.push(line) });
  expect(readFileSync(path.join(root, "jigs-generated.ts"), "utf8")).toBe(
    "// this factory installed me",
  );
  expect(lines).toEqual(["generated jigs/steps.ts and jigs/routines.ts — review and commit them"]);
});

test("generation explains when the factory has not installed jigs", async () => {
  await expect(generateIntegration({ cwd: factory(), out: () => {} })).rejects.toThrow(
    /not installed/,
  );
});

test("a factory from an earlier release loses jigs.ts and its old imports", () => {
  const root = factory();
  writeFileSync(path.join(root, "jigs.ts"), "// generated by an earlier jigs\n");
  writeFileSync(
    path.join(root, "package.json"),
    JSON.stringify({
      name: "acme",
      imports: { "#jigs": "./jigs.ts", "#blocks/*": "./blocks/*.ts", "#steps/*": "./steps/*.ts" },
      scripts: { test: "vitest run" },
    }),
  );
  const lines: string[] = [];
  migrateRetiredLayout(root, (line) => lines.push(line));

  expect(existsSync(path.join(root, "jigs.ts"))).toBe(false);
  const manifest = JSON.parse(readFileSync(path.join(root, "package.json"), "utf8"));
  expect(manifest.imports).toEqual({ "#jigs/*": "./jigs/*.ts" });
  expect(manifest.scripts).toEqual({ test: "vitest run" });
  expect(lines).toEqual([
    "deleted jigs.ts; its steps now live in jigs/steps.ts",
    "removed #jigs from package.json imports",
    "removed #blocks/* from package.json imports",
    "removed #steps/* from package.json imports",
    "added #jigs/* → ./jigs/*.ts to package.json imports",
  ]);
});

test("a current factory is left as it is, and says nothing", () => {
  const root = factory();
  const manifest = `${JSON.stringify({ name: "acme", imports: { "#jigs/*": "./jigs/*.ts" } }, null, 2)}\n`;
  writeFileSync(path.join(root, "package.json"), manifest);
  const lines: string[] = [];
  migrateRetiredLayout(root, (line) => lines.push(line));

  expect(readFileSync(path.join(root, "package.json"), "utf8")).toBe(manifest);
  expect(lines).toEqual([]);
});
