// Generates src/prompts/defaults.ts from every src/prompts/*.md. Run with
// `pnpm --filter jigs gen:prompts`; defaults.test.ts fails if the two drift.

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const dir = fileURLToPath(new URL("../src/prompts", import.meta.url));

const constName = (file: string) =>
  `${path
    .basename(file, ".md")
    .replace(/-(.)/g, (_match, char: string) => char.toUpperCase())}Prompt`;

const lines = readdirSync(dir)
  .filter((file) => file.endsWith(".md"))
  .sort()
  .map(
    (file) =>
      `export const ${constName(file)} = ${JSON.stringify(readFileSync(path.join(dir, file), "utf8"))};`,
  );

writeFileSync(
  path.join(dir, "defaults.ts"),
  `// Generated by scripts/gen-prompts.ts from src/prompts/*.md — edit the markdown, not this file.\n\n${lines.join("\n\n")}\n`,
);
