import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

// Where `prepare()` writes the generated sources, relative to the factory
// root. They live with the writer rather than with the Nitro config that
// serves them, so the file a reader opens to see what is generated is also
// the file that says where it lands.
export const GENERATED_DIR = ".jigs";
export const GENERATED_ENTRY_FILE = "server.ts";
export const GENERATED_SCHEDULES_FILE = "schedules.ts";

// A real entry file, never a nitro alias: the workflow builder runs its own
// discovery pass that does not honour nitro aliases, so an alias would build
// clean for Nitro and silently emit a manifest with no steps in it.
//
// Generated every build rather than scaffolded once by `jigs init`, even
// though the content does not vary today: this is jigs' own code sitting in
// the factory's tree. A copy made at init time would go stale in every
// existing factory the day this seam changes, with nothing to say so.
const ENTRY_SOURCE = `// Generated by \`jigs build\` — do not edit.
import { createApp } from "@salimhamed/jigs/app";
import factory from "../jigs.config.ts";

export default createApp(factory);
`;

// A nitro plugin rather than a line in the entry above, so the ticker starts
// beside the World it fires runs into rather than when the route module is
// evaluated. It has to live here because only the factory's own tree can
// import its compiled pipelines.
const SCHEDULES_SOURCE = `// Generated by \`jigs build\` — do not edit.
import { startSchedules } from "@salimhamed/jigs/schedules";
import factory from "../jigs.config.ts";

export default () => {
  startSchedules(factory);
};
`;

/**
 * Writes everything a factory's Nitro build needs but does not keep in git,
 * under `<factoryRoot>/.jigs/`, and returns the entry's absolute path. The
 * file is rewritten in full, so running this twice is running it once.
 */
export function prepare(factoryRoot: string): string {
  const generated = path.join(factoryRoot, GENERATED_DIR);
  mkdirSync(generated, { recursive: true });

  const entry = path.join(generated, GENERATED_ENTRY_FILE);
  writeFileSync(entry, ENTRY_SOURCE);
  writeFileSync(
    path.join(generated, GENERATED_SCHEDULES_FILE),
    SCHEDULES_SOURCE,
  );
  return entry;
}
